### ISSUE TITLE
Lab 6.2 missing sql files for windows lab

### ISSUE THREAD

**Issue by josephoaks** [puppetlabs/ilt-practitioner-issues#15]
## Describe the Change You Would Like
The noted files are not present on the Windows AMI, causing the sql ordering lab to fail.

**Comment by golflimaechoecho** [comment]
This is still unresolved (class 2260)

**Comment by greglarkin** [comment]
The SQL Server download files have been added to the Windows student AMI build, but perhaps a new version has not been released yet: https://github.com/puppetlabs/courseware-lms-win-student-ami/commit/aa78465cec739353b1f1510649774304d4a08896#diff-ce55b654b153ebf2704031b99733fff0R195

**Comment by greglarkin** [comment]
Closing as duplicate

**Comment by greglarkin** [comment]
https://github.com/puppetlabs/ilt-practitioner-issues/issues/40
