### ISSUE TITLE
Link boxes on Appendix page do not display corrrectly with chrome plugin

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#17]
## Describe the Bug
With Gitbook Plugin for Google Chrome v1.1, the Appendix page does not display properly.

Chrome (with plugin)
<img width="1315" alt="puppet_practitioner_gitbook_appendix" src="https://user-images.githubusercontent.com/62140283/94212170-cc4a3480-ff16-11ea-838d-b2bb2d6f5ab9.png">

Same page on Firefox (without plugin)
<img width="1146" alt="puppet_practitioner_gitbook_appendix_firefox" src="https://user-images.githubusercontent.com/62140283/94212177-ceac8e80-ff16-11ea-8fe3-2536e397e168.png">

## Expected Behavior
The link boxes on the Appendix page (Git, Git tutorial, Resources, Vim cheat sheet) should display with text (or be replaced with another style that is compatible with the plugin)

## Steps to Reproduce
1. Go to Appendix page, eg: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/appendix
2. Confirm empty boxes are displayed. The links still work, but you have to hover and check the status bar to see which box goes where

## Environment
 - https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/
 - Google Chrome
 - Plugin version 1.1

**Comment by greglarkin** [comment]
@golflimaechoecho I googled for the chrome plugin in question but did not locate it. Can you link me to the proper plugin so I can install it and reproduce this problem?

**Comment by golflimaechoecho** [comment]
@greglarkin the referenced chrome plugin was provided by @josephoaks in September to "[add] left/right arrow key navigation [and] also modified CSS that makes the Presentation much cleaner"

https://puppet.slack.com/archives/CF466LW2W/p1600713807001800

https://github.com/puppetlabs/ilt-getting-started-with-puppet/blob/master/gitbook-plugin-instructions.md
https://github.com/puppetlabs/ilt-practitioner/blob/master/gitbook-plugin-instructions.md

**Comment by greglarkin** [comment]
I could not get the autogenerated boxes to appear even after modifying the page in a few different ways, so I added an explicit set of bullet points. This seems to match other title pages in the course materials too: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/appendix
