### ISSUE TITLE
Agenda does not correspond with Lessons

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/ilt-practitioner-issues#19]
## Describe the Bug

The Agenda shown at the start of the course does not correspond to the actual lessons included in the course. 

Discrepancies: 

* *Using Puppet data* is shown on the Agenda for Day 1, however it is covered in Lesson 13, which would be on Day 3. 
* *Data structures in the Puppet DSL* and *New language constructs in Puppet 6* appear in the Agenda for Day 1 however they are covered in the one lesson, *Lesson 6: Language constructs*
* *Orchestration with Puppet Tasks* is shown on the Agenda for Day 3, but it covered in Day 1, Lesson 3, *Puppet tasks*.
* *Capstone Lab* is shown on Agenda for Day 3, but there is no lesson for it included in the course.
* The following lessons are not represented in the Agenda: 
  * Lesson 1: Classroom environment
  * Lesson 2: Editing code in the classroom

The Agenda should correspond to the actual lessons, for example as follows (taken from the table of contents):

Day 1

Course overview
Lesson 1: Classroom environment
Lesson 2: Editing code in the classroom
Lesson 3: Puppet tasks
Lesson 4: Review of Puppet basics
Lesson 5: Resource types

Day 2

Lesson 6: Language constructs
Lesson 7: Ordering techniques
Lesson 8: Facts and functions
Lesson 9: File manipulation
Lesson 10: Data separation

Day 3

Lesson 11: Architecting modules
Lesson 12: Roles and profiles
Lesson 13: Using Puppet data
Lesson 14: Introduction to module testing

## Expected Behavior

Agenda should be accurate, and in particular not include things that the course does not cover.

## Steps to Reproduce

Compare the lessons of course (eg from the table of contents, or outline view) with the listing on the "Course agenda" page, eg https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/course-overview-1/course-agenda

## Environment

Puppet Practitioner, Gitbook https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/course-overview-1/course-agenda

**Comment by greglarkin** [comment]
Thank you for providing the updated agenda, and it has been changed in the latest Gitbook
