### ISSUE TITLE
Lab 4.3 Solution for windows - incorrect syntax

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#25]
## Describe the Bug

Lab 4.3 Solution provided for windows has incorrect syntax for epp(), should be comma not full stop after epp file name.

```puppet
# A description of what this class does
#
# @summary A short summary of the purpose of this class
#
# @example
#   include review::hello
class review::hello {
  file { 'C:/Users/Administrator/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1':
    ensure  => file,
    owner   => 'Administrator',
    content => epp('review/hello.epp'. { fqdn => $facts['networking']['fqdn'], uptime => $facts['system_uptime']['uptime'] }),
  }
}
```

## Expected Behavior
Correct syntax provided in lab solution.

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-4-puppet-basics-review/lab-4.3-manage-a-file -> Lab 4.3: Solution - Windows
2. Observe incorrect syntax for epp()
3. Attempt to run provided solution on host, observe the following error

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Syntax error at '{' (file: /etc/puppetlabs/code/environments/student16/modules/review/manifests/hello.pp, line: 12, column: 42) on node 2260win16.classroom.puppet.com
```

## Environment
https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-4-puppet-basics-review/lab-4.3-manage-a-file

**Comment by greglarkin** [comment]
Fixed in the current version of the Gitbook
