### ISSUE TITLE
Lesson 5 Resource defaults example formatting

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#26]
## Describe the Bug
The formatting for resource default syntax examples on the subsequent info tab requires improvement.

- `default` should be on new line, not on the same line as `file (`

- single resources should not be declared in array syntax

```
file { default:
  ensure => file,
  owner  => 'root',
  group  => 'web-users',
  mode   => '0644',    # directory permissions promoted to 0755
  ;
  [ '/etc/httpd/README' ]: content => 'Apache mananged by Puppet',
  ;
  [ '/etc/httpd', '/etc/httpd/conf.d' ]:
    ensure => directory,
    group  => 'root',
  ;
  [ '/etc/httpd/conf.d/default.conf' ]:
    content => epp('apache/default.conf.epp'),
  ;
  [ '/etc/httpd/conf.d/secure.conf' ]:
    mode    => '0640',
    content => epp('apache/secure.conf.epp'),
  ;
}
```

Similar applies to the splat operator example

```
$file_ownership = {
  ensure => file,
  owner  => 'root',
  group  => 'web-users',
  mode   => '0644',    # directory permissions promoted to 0755
}

file { default:
  * => $file_ownership,
  ;
  [ '/etc/httpd', '/etc/httpd/conf.d' ]:
    ensure => directory,
    group  => 'root',
  ;
  [ '/etc/httpd/conf.d/default.conf' ]:
    content => epp('apache/default.conf.epp'),
  ;
  [ '/etc/httpd/conf.d/secure.conf' ]:
    mode    => '0640',
    content => epp('apache/secure.conf.epp'),
  ;  
}
```

## Expected Behavior

Example provided in subsquent info complies/is consistent with style guide

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/resource-defaults
2. Click on 'Subsequent info' tab

## Environment
https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/resource-defaults

## Additional Context
https://puppet.com/docs/puppet/6.18/style_guide.html

**Comment by greglarkin** [comment]
Fixed in changeset to be merged into Gitbook
