### ISSUE TITLE
Lab 7.1 windows solution does not conform to style guide

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#27]
## Describe the Bug

```
class ordering::sqlserver {
  contain ordering::config
  contain ordering::logins
  contain ordering::users

  Class['ordering::config'] ->
    Class['ordering::logins'] ->
    Class['ordering::users']
}
```

pdk validate gives errors:

```
warning: puppet-lint: manifests/sqlserver.pp:12:29: arrow should be on the right operand's line
warning: puppet-lint: manifests/sqlserver.pp:13:31: arrow should be on the right operand's line
```

Also: init.pp gives error "double quoted string containing no variables"; users.pp, logins.pp give warnings for trailing whitespace

## Expected Behavior

provided solutions should conform with style guide/not result in pdk warnings.

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-7-ordering-techniques/lab-7.1-ordering-methods
2. Click on 'Lab 7.1: Solution - Windows'

## Environment
Windows

**Comment by greglarkin** [comment]
Fixed in changeset to be merged into Gitbook
