### ISSUE TITLE
Lab 7.1 Window incorrect commit message

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#28]
## Describe the Bug

Lab 7.1 adds the ordering module, Step 7 to commit changes refers to system module

Step 7 of Lab 7.1 for Windows: "Click the ellipsis and then click Commit Staged and enter Add system module to commit the changes."

## Expected Behavior

Reference correct module in instructions/commit message

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-7-ordering-techniques/lab-7.1-ordering-methods
2. Click on 'Lab 7.1 Windows'

## Environment
https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-7-ordering-techniques/lab-7.1-ordering-methods

**Comment by greglarkin** [comment]
Fixed
