### ISSUE TITLE
Lesson 5 Defined resource types parameters not passed to epp template

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#29]
## Describe the Bug

On the Defined resource types slide: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/defined-resource-types-1

A student noticed that the parameters are not being passed to the template

```define apache::vhost (
  $docroot,
  $port       = '80',
  $priority   = '10',
  $options    = 'Indexes MultiViews',
  $vhost_name = $title,
  $servername = $title,
  $logdir     = '/var/log/httpd',
) {
  file { "/etc/httpd/conf.d/${title}.conf":
    ensure  => file,
    owner   => 'apache',
    group   => 'apache',
    mode    => '0644',
    content => epp('apache/vhost.conf.epp'),
  }
}
```

probably result of converting from erb to epp but not passing the params as required by epp

## Expected Behavior

Example should demonstrate parameters being passed to epp template per correct usage

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/defined-resource-types-1
2. Click on second 'Defined resource types' slide (title "Implemented with Puppet code" with code example for apache::vhost)

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

## Additional Context

https://puppet.com/docs/puppet/6.18/lang_template_epp.html

**Comment by greglarkin** [comment]
Added a changeset to include the variables to the epp() function call.
