### ISSUE TITLE
Lesson 6 filter() example obsolete hiera() call

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#31]
## Describe the Bug

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-6-language-constructs/filter

The filter() example/subsequent info still references hiera() function; it would be helpful if this also included a list of package names to demonstrate, but at the very least should remove the call to deprecated function.

```
hiera('packages').filter |String $pkg| { $pkg =~ /^dev-/}.each |String $pkg| {
    package { pkg:
        ensure => present,
    }
}
```

## Expected Behavior

update/remove hiera() reference

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-6-language-constructs/filter
2. Click on 'Subsequent info' tab

## Environment

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-6-language-constructs/filter

## Additional Context

https://puppet.com/docs/puppet/6.18/function.html#hiera

**Comment by greglarkin** [comment]
Fixed in changeset to be merged into Gitbook
