### ISSUE TITLE
Lab 8.1 include examples for --custom-dir, FACTERLIB

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#33]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-8-facts-and-functions/lab-8.1-create-a-custom-fact

> 6. Syntax check and test your new fact locally.
> `/opt/puppetlabs/puppet/bin/ruby -c lib/facter/default_realm.rb`
> `RUBYLIB="lib" facter default_realm`

Should this also be an opportunity to demonstrate using --custom-dir, FACTERLIB?

https://puppet.com/docs/puppet/6.17/custom_facts.html#using-the-custom-dir-command-line-option

`facter -p --custom-dir ./lib/facter default_realm`

https://puppet.com/docs/puppet/6.17/custom_facts.html#using-the-facterlib-environment-variable

`FACTERLIB=./lib/facter facter default_realm`

The **Distributing facts** slide mentions FACTERLIB but then shows RUBYLIB in the example

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-8-facts-and-functions/distributing-facts

> Test facts locally by setting the FACTERLIB or RUBYLIB environment variables.

```
[root@training ~]# export PROD=/etc/puppetlabs/code/environments/production/
[root@training ~]# export RUBYLIB=${PROD}/modules/custom/lib
[root@training ~]# facter role
Desktop class machine
```

## Describe the Solution You Would Like

Include usage examples for --custom-dir and FACTERLIB

**Comment by golflimaechoecho** [comment]
see also [testing custom fact via RUBYLIB causes segfaults](https://tickets.puppetlabs.com/browse/FACT-1349)

`$FACTERLIB`, `--custom-dir` (and `$LOAD_PATH`) are current documented methods to load custom facts, so this would also be more consistent with custom facts documentation

**Comment by josephoaks** [comment]
"The Distributing facts slide mentions FACTERLIB but then shows RUBYLIB in the example" it also states clearly" the slide clearly states "Test facts locally by setting the FACTERLIB or RUBYLIB environment variables." This is an acceptable usage.

We can update the lab to show using FACTERLIB= as well, this would be great addition.

**Comment by golflimaechoecho** [comment]
>  the slide clearly states "Test facts locally by setting the FACTERLIB or RUBYLIB environment variables." This is an acceptable usage.

fyi RUBYLIB is not consistent with approach mentioned in [latest custom facts overview documentation](https://puppet.com/docs/puppet/7.6/custom_facts.html#using-the-custom-dir-command-line-option), eg: refers to using LOAD_PATH instead

> ### Loading custom facts
> Facter offers multiple methods of loading facts.
> These include:
> - `$LOAD\_PATH`, or the Ruby library load path.
> - The `--custom-dir` command line option.
> - The environment variable `FACTERLIB`.
