### ISSUE TITLE
Lab 9.1 Windows incorrect value for runinterval

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#35]
## Describe the Bug

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-9-file-manipulation/lab-9.1-managing-file-content

Provided solution states setting runinterval to 60 minutes; the code shown sets to 60 seconds

```
  file_line { 'set runinterval to 60 minutes':
    ensure => present,
    path   => 'C:/ProgramData/PuppetLabs/puppet/etc/puppet.conf',
    line   => 'runinterval = 60',
  }
```

https://puppet.com/docs/puppet/6.17/configuration.html#runinterval

## Expected Behavior

Correct value used to set runinterval, ie: 60m or 3600 (seconds)

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-9-file-manipulation/lab-9.1-managing-file-content
2. Click on 'Lab 9.1: Solution - Windows'

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by greglarkin** [comment]
Fixed in new version of Gitbook
