### ISSUE TITLE
Lesson 10 data separation "Using the default merge options"

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#37]
## Describe the Bug

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/using-the-default-merge-options

Subsequent info tab is obsolete

> The Long Term Support version of this code would be: .... (same code as main slide as this is leftover/artifact from hiera() calls that have been replaced)

## Expected Behavior

Subsequent info is removed as this slide is incorrect/obsolete

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/using-the-default-merge-options
2. Click on 'Subsequent info' tab
3. Compare code to main slide - they are the same as the old hiera() call has been replaced with lookup() in both cases

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by greglarkin** [comment]
Fixed in changeset to be merged into Gitbook
