### ISSUE TITLE
Lesson 10 replace create_resources with iteration

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#38]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/using-the-hash-merge-option

hash merge example uses create_resources in code example - can this be replaced with iteration (each()) to discourage use of create_resources() and be consistent with Lesson 6 language constructs

```
$users = lookup('users::sysadmins', { 'merge' => 'hash' })
create_resources('user', $users)
```

## Describe the Solution You Would Like

Replace create_resources() example with iteration (each()) to be consistent with messaging in Lesson 6 language constructs

**Comment by greglarkin** [comment]
Fixed in changeset to be merged into Gitbook
