### ISSUE TITLE
Lab 14.1 refers to downloads page from showoff instead of new/replacement gitlab repo (apache)

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#39]
## Describe the Bug

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-14-introduction-to-module-testing/lab-14.1-unit-test-a-class

> 1. Download and uncompress the starter module from the instructor.
>     - `wget https://classXXXX-slides.classroom.puppet.com/file/_files/share/testing_apache.tar.gz`
> (Copy the link from your downloads page.)
>    - `tar -xvzf testing_apache.tar.gz`
>    - `cd apache`

The provided solution output is also inconsistent, eg: linux solution shows files/windows.conf (in addition to debian, redhat), windows solution only shows (debian|redhat).conf files

## Expected Behavior

The contents appear to have been added to gitlab as a repo eg: https://classXXXX-gitlab.classroom.puppet.com/puppet/apache; the instructions should be updated to reflect the correct location/method to retrieve the class for testing. The classroom/student deploy key also needs to be added to this repo to be able to clone/push (key had not been added for class 2260)

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-14-introduction-to-module-testing/lab-14.1-unit-test-a-class
2. Click on 'Lab 14.1: Unit test a class - Linux' or 'Lab 14.1: Unit test a class - Windows' (same issue on both)
3. View instructions to obtain testing_apache.tar.gz (still refers to showoff downloads page)

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by jessereynolds** [comment]
Instructions need changing to just execute `git clone git@gitlab.classroom.puppet.com:puppet/apache.git` to get the module.

**Comment by tuxmea** [comment]
I can confirm that deploy key is working when using git url and that the slides still show the old download link.
Course 2239

**Comment by martezr** [comment]
The instructions have been updated to reference the gitlab apache repository instead of the old showoff download link.
