### ISSUE TITLE
Practitioner lab 6.2 Windows - SQL Server 2019 installer files are missing

### ISSUE THREAD

**Issue by 16c7x** [puppetlabs/ilt-practitioner-issues#40]
## Describe the Bug
Applying the code returns 
Error: Could not set 'present' on ensure: No such file or directory - CreateProcess (file: /etc/puppetlabs/code/environments/student0/modules/system/manifests/admins.pp, line: 8)
First this was because Puppet could not find the file.
Once the file was downloaded it could find it but as it was an iso it could not find setup.exe.

## Expected Behavior
Puppet agent should apply the catalog.

## Steps to Reproduce
Follow the instructions in the lab, I followed the instructions as did 2 students, all of us got the same result.

Error: Could not set 'present' on ensure: No such file or directory - CreateProcess (file: /etc/puppetlabs/code/environments/student0/modules/system/manifests/admins.pp, line: 8)

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

## Additional Context
Fixed the problem localy by

source => 'C:/Users/Administrator/Downloads/SQLServer2019-DEV-x64-ENU',
Change to 
source => 'D:/',

Download the iso from 
https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-x64-ENU-Dev.iso
We should update the classroom vm build so this is already on the student machine.

Then double click on the iso file so it mounts as a D: drive.

Rerun puppet agent -t

**Comment by greglarkin** [comment]
The code to automatically download and extract the SQL Server 2019 installer files has been added to the Windows student AMI, but a new build may be needed to get the image in place for future classrooms: https://github.com/puppetlabs/courseware-lms-win-student-ami/pull/27/files#diff-ce55b654b153ebf2704031b99733fff0R195

**Comment by golflimaechoecho** [comment]
For reference, the installer file was still missing for class 2259 (27-29 Oct)

**Comment by greglarkin** [comment]
![image](https://user-images.githubusercontent.com/4807374/98973528-b72a6480-24c8-11eb-8da6-6fedd1a5d05f.png)
Sorry for the delay, but the Windows AMI has now been updated.
