### ISSUE TITLE
14.1 students don't have permissions to pull the apache module

### ISSUE THREAD

**Issue by 16c7x** [puppetlabs/ilt-practitioner-issues#41]
## Describe the Bug
Students do not have permissions to pull the apache module from gitlab.

## Expected Behavior
Expect git clone git@gitlab.classroom.puppet.com:puppet/apache.git to pull down the apache module.

## Steps to Reproduce
As a student tun  git clone git@gitlab.classroom.puppet.com:puppet/apache.git

## Additional Context
```
[centos@2262nix0 ~]$ git clone git@gitlab.classroom.puppet.com:puppet/apache.git
Cloning into 'apache'...
> GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[centos@2262nix0 ~]$ git clone git@gitlab.classroom.puppet.com:puppet/time.git
Cloning into 'time'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 12 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (12/12), done.
[centos@2262nix0 ~]$
```

**Comment by tuxmea** [comment]
The deploy key is missing on that repo.
To be able to push back into the apache module, the deploy key must be added with write pemissions.

**Comment by golflimaechoecho** [comment]
see also https://github.com/puppetlabs/ilt-practitioner-issues/issues/39

**Comment by jessereynolds** [comment]
The deploy key was present on the apache module in class 2259 taught on 27 Oct. I think this one can be closed?

**Comment by 16c7x** [comment]
Tested this lin class 2319 and everything is working so closing.
