### ISSUE TITLE
Lab 14.1 Should be made clear that this lab should be run as root or lab 14.2 fails.

### ISSUE THREAD

**Issue by 16c7x** [puppetlabs/ilt-practitioner-issues#42]
## Describe the Bug
It needs to be clear that this lab should be done as the root user. 
Several students tried it as the centos user, it worked but when we got to lab 14.2 it caused a lot of hold ups while things were rejigged to make that lab work.

## Expected Behavior
The lab works the impact of using the wrong user is not seen until the following lab.

## Steps to Reproduce
Run lab 14.1 as centos and then attempt lab 14.2

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by josephoaks** [comment]
Very first lab has a big callout stating that all labs are to be run as root.
