### ISSUE TITLE
(formatting) Course overview - Product updates

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#45]
## Describe the Bug

In the Course overview, on the Product updates slide, there appears to be a missing newline in the "Platforms removed" section (for Master)

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/course-overview-1/product-updates

screenshot: ![practitioner_product_updates_slide](https://user-images.githubusercontent.com/62140283/97125922-85579500-1789-11eb-82f2-ddceef94e5be.png)

## Expected Behavior

Master should start on a new line

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by greglarkin** [comment]
This appears to have been fixed already by someone else: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/course-overview-1/product-updates
