### ISSUE TITLE
Lesson 3 Tasks vs plans comparison incorrect

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#46]
## Describe the Bug

Practitioner Lesson 3 - Tasks vs plans slide appears to have incorrect description for plans - the text for plans appears to be more applicable to imperative (bolt) vs declarative (agent) puppet rather than tasks vs plans.

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-3-puppet-tasks/tasks-vs-plans
![tasks_vs_plans_updated](https://user-images.githubusercontent.com/62140283/97131033-3153ad00-1797-11eb-9bf6-fbdb921c8a89.png)

In Practitioner. the diagram shows:

=====

Task

- Run it now
- Ad hoc, one-off

Plan

- Run it in the future
- Repeatable, reusable, building block

=====

Contrast to similar/equivalent slides in GSWP:

### Tasks vs plans [GSWP Lesson 2: Bolt]

https://puppet-kmo.gitbook.io/gswp/-MFBOrY4wkT-M5izoA2y/table-of-contents/lesson-2-bolt/tasks-vs-plans

|Tasks|Plans|
|---|---|
|Single action|Sets of tasks and logic|
|Written in any programming language|Written in the Puppet language|
|Includes metadata|Complex operations|

<img width="924" alt="gswp_tasks_vs_plans" src="https://user-images.githubusercontent.com/62140283/97131419-3ebd6700-1798-11eb-8ba5-3fb22d56c7e8.png">

### Imperative vs declarative puppet [GSWP Lesson 4: Introduction to Declarative Puppet]

https://puppet-kmo.gitbook.io/gswp/-MFBOrY4wkT-M5izoA2y/table-of-contents/lesson-4-introduction-to-declarative-puppet/imperative-vs.-declarative-puppet

|Imperative|Declarative|
|---|---|
|Run it now|Run it in the future|
|Ad-hoc, one-off|Repeatable, reusable, building block|
|Bolt|Puppet agent|

<img width="783" alt="gswp_imperative_vs_declarative" src="https://user-images.githubusercontent.com/62140283/97131406-336a3b80-1798-11eb-8be5-ccc5c1dcd072.png">

## Expected Behavior

The slide should accurately describe the differences between tasks and plans.

It may also be helpful for the Practitioner course to include an extra slide/diagram for imperative vs declarative to make the distinction between [tasks+plans] vs [agent] clearer - the current imperative vs declarative has the task based vs model based. blueprint vs house tasks examples, however then it skips straight to "Putting it together" (doesn't have a pretty picture comparing tasks to agent, etc)

## Environment

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/

**Comment by greglarkin** [comment]
@golflimaechoecho I updated the Practitioner "tasks vs plans" page to match the one found in GSWP since the bulleted list under the image makes more sense. I have not built additional pages yet as suggested.

**Comment by golflimaechoecho** [comment]
@greglarkin just to check, is the above change waiting on merge or should it be visible now?

Looking at https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-3-puppet-tasks/tasks-vs-plans it doesn't seem to have updated yet

**Comment by greglarkin** [comment]
> @greglarkin just to check, is the above change waiting on merge or should it be visible now?
> 
> Looking at https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-3-puppet-tasks/tasks-vs-plans it doesn't seem to have updated yet

Ah yes, it is still waiting for merge. Please check this link to see if you can view the changesets prior to merge. I also added an image and rearranged the text on the "Imperative vs Declarative" page.

https://app.gitbook.com/invite/puppet-kmo?invite=-M5OLyoVJHPI-DdmZdg5

**Comment by golflimaechoecho** [comment]
Hi @greglarkin - thanks for confirming. I've tried the link; it doesn't seem to have access to view the changesets, which is fine as I don't need to see the changeset itself, just checking that it was still pending an action/it hadn't done some strange caching in the live/current version :)

**Comment by greglarkin** [comment]
> Hi @greglarkin - thanks for confirming. I've tried the link; it doesn't seem to have access to view the changesets, which is fine as I don't need to see the changeset itself, just checking that it was still pending an action/it hadn't done some strange caching in the live/current version :)

Ok, sure thing! Here is screenshot of the updated imperative vs declarative page:

![image](https://user-images.githubusercontent.com/4807374/101705638-3f564800-3a3c-11eb-9f57-28565bdb6977.png)

And here's the updated tasks vs. plans:

![image](https://user-images.githubusercontent.com/4807374/101705671-509f5480-3a3c-11eb-89c9-0dec39231040.png)

These should be merged within the next couple of days.
