### ISSUE TITLE
Lesson 3 Command example 2: Remote Puppet agent runs

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#47]
## Describe the Bug

Lesson 3 Command example 2: Remote Puppet agent runs - example job run has inconsistent output

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-3-puppet-tasks/command-example-2-remote-puppet-agent-runs

`puppet job run` example is using query for `gregs.puppetlabs.vm`, however output shown appears to be for node `puppet.classroom.puppet.com`

```
puppet job run --query 'nodes { certname = "gregs.puppetlabs.vm" }'

Starting deployment ...

+-------------------+-------+
| Job ID            | 3     |
| Target            | query |
| Concurrency Limit | None  |
| Nodes             | 1     |
+-------------------+-------+

Application instances: 0

Node run order (nodes in level 0 run before their dependent nodes in level 1, etc.):
0 -----------------------------------------------------------------------
puppet.classroom.puppet.com

New job created: 3
Started puppet run on puppet.classroom.puppet.com ...
Finished puppet run on puppet.classroom.puppet.com - Success!
    Resource events: 0 failed 0 changed 1,325 unchanged 0 skipped 0 noop
    Report: https://puppet.classroom.puppet.com/#/run/jobs/3/nodes/puppet.classroom.puppet.com/report

Success! 1/1 runs succeeded.
Duration: 55 sec
```

## Expected Behavior

Query used to run job should match output

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by martezr** [comment]
The query has been corrected to reference puppet.classroom.puppet.com instead of gregs.puppetlabs.vm to properly align with the command output in the example.
