### ISSUE TITLE
Lab 5.2: Defined type - Linux lab steps not consistent with Windows steps

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#48]
## Describe the Bug

Lab 5.2: Defined types - Linux is missing a step to add/commit/push the updates for this lab to git.
While this does not break anything as `system::managed_users` is only intended to be applied locally, it is not consistent with the Windows lab (which does include steps to commit changes even though they are also only applied locally on Windows).

## Steps to Reproduce
1. Go to https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/lab-5.2-defined-type
2. Click on Linux and Windows tabs; Windows has section below to commit, Linux does not have equivalent section

> Commit and push your changes
> 1. Press Crtl+Shift+G to enter the source control pane. Click ...->Stage All Changes to stage the file changes.
> 2. Click ...->Commit Staged and enter Add managed_user defined type to commit the changes.
> 3. Click ...->Push to push your code changes back to your branch in the remote repository.

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by greglarkin** [comment]
Updated here: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/lab-5.2-defined-type
