### ISSUE TITLE
Lab 5.2: Defined types - Linux - output does not match steps

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#49]
## Describe the Bug

Under 'Test the effects of your class' https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/lab-5.2-defined-type#test-the-effects-of-your-class

Instruction is "Switch users on your node to one of the new users: `sudo -su kaitlin`"

However the output shown is:

```
# sudo su - kaitlin
______________
< Hello there! >
[...]
```

## Expected Behavior

Command shown in sample output matches instructions provided

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by greglarkin** [comment]
Updated and merged: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-5-resources-types/lab-5.2-defined-type#test-the-effects-of-your-class
