### ISSUE TITLE
Lab 8.1 Windows - bios_version includes review::hello text

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#50]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]

In [Lab 8.1](https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-8-facts-and-functions/lab-8.1-create-a-custom-fact) a `bios_version` custom fact is created for Windows using a powershell command to generate the output

However as `C:/Users/Administrator/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1` is managed in [Lab 4.3](https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-4-puppet-basics-review/lab-4.3-manage-a-file), the fact ends up looking like:

|Fact|Value|
|:---|:----|
|bios_version|Hello from {fqdn}. I have been running for {N} days.<br />This machine is managed with Puppet.<br />Revision: 1.221|

ie: using the provided solution results in he powershell profile text being included in the fact

## Describe the Solution You Would Like

bios_version fact contains relevant information only (not motd/hello profile text)

## Describe Alternatives You've Considered

This is possibly useful as a discussion point/illustrative example to point out the pitfalls/considerations when writing custom facts (ie: make sure the fact is written to parse correctly/strip out unnecessary information)

However it would probably be better to demonstrate the extra lines in lab walkthrough with the instructor, rather than having it as the default provided solution

**Comment by zoojar** [comment]
I normally suggest fixing this with:

`Facter.add("bios_version") do
    confine :kernel => 'windows'
    setcode do
      Facter::Core::Execution.execute('C:/Windows/System32/WindowsPowerShell/v1.0/Powershell.exe -noprofile "(Get-WmiObject -Class Win32_Bios | Select-Object -First 1).Name"')
    end
end
`

**Comment by greglarkin** [comment]
> I normally suggest fixing this with `-noprofile`:
> 
> `Facter.add("bios_version") do confine :kernel => 'windows' setcode do Facter::Core::Execution.execute('C:/Windows/System32/WindowsPowerShell/v1.0/Powershell.exe -noprofile "(Get-WmiObject -Class Win32_Bios | Select-Object -First 1).Name"') end end `

Thank you for the information @zoojar , and I have updated the Gitbook with the `-noprofile` flag. The change is pending merge and should appear in the live Gitbook very shortly.
