### ISSUE TITLE
hiera functions slide - says LTS only has hiera function not lookup

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/ilt-practitioner-issues#51]
## Describe the Change You Would Like

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/hiera-functions

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/using-the-default-merge-options

hiera functions and default merge options pages - subsequent info says 'lookup' is not available in the current LTS and you have to use 'hiera'. This is not true - just change the language to talk about versions of puppet / PE where the lookup() function was introduced.

**Comment by golflimaechoecho** [comment]
The issue with 'default merge options' Subsequent Info was raised in https://github.com/puppetlabs/ilt-practitioner-issues/issues/37; marked as "Fixed in changeset to be merged into Gitbook" however class 2259 doesn't have that yet

**Comment by greglarkin** [comment]
Updated the function descriptions with more concise information: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/hiera-functions
