### ISSUE TITLE
Lesson 10 Data Separation - replace hieradata with data

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#52]
## Describe the Bug

replace references to `hieradata` path with `data`

eg: on slides:

- Sample configuration: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/sample-configuration
- Using the default merge options: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/using-the-default-merge-options (`cat ${environment}/hieradata/hosts/kermit.puppetlabs.vm.yaml`)
- Using the unique merge option: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/using-the-unique-merge-option (middle code snippets)
- Using the hash merge option: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/using-the-hash-merge-option
- Including a list of classes: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/including-a-list-of-classes
- Automatic parameter lookup: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-10-data-separation/automatic-parameter-lookup (bottom code snippet)

## Expected Behavior

Slides in Lesson 10 should reflect hiera 5 data dir location

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by greglarkin** [comment]
I have opened a change request in the Gitbook, and thank you for the report!
