### ISSUE TITLE
Lesson 11 - reorder content on Code defensively slide

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#53]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]

https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-11-architecting-modules/code-defensively

> - It is better to fail compilation than to enforce unpredictable configuration.
> - Case statements should have default cases.
> - Selectors should normally fail on unexpected values by not including a default.
> <code snippet>

The code snippet shows a case statement so should probably be after the case statement bullet point

The wording of the Selector bullet point is slightly ambiguous (additionally confusing due to current ordering)

## Describe the Solution You Would Like

Case statement example should directly follow the case statement bullet point.

Reword Selector bullet point to be clearer/less ambiguous (eg: "Selectors will fail on unexpected values if no default is included"); possibly also include a code snippet/example to illustrate

**Comment by greglarkin** [comment]
Updated and merged: https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-11-architecting-modules/code-defensively
