### ISSUE TITLE
Virtual classroom environment diagram improvements

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/ilt-practitioner-issues#55]
## Describe the Change You Would Like

In lesson 2, virtual classrom environment - the diagram should be updated to say 'student1' etc rather than 'bob' etc. 

Also, show each student's branch as a branch, not as a separate repo as it looks like now. 

![Screen Shot 2020-11-15 at 10 12 49 pm](https://user-images.githubusercontent.com/391439/99183455-fd651980-278f-11eb-9da0-189f7bcd7002.png)

**Comment by greglarkin** [comment]
Now fixed by @taraswenson : https://puppet-kmo.gitbook.io/puppet-practitioner/-MFBOjyVETcxjlTAR_Hx/table-of-content/lesson-2-editing-code-in-the-classroom/virtual-classroom-environment
