### ISSUE TITLE
Lab 10.1 - Instructions don't match the solution

### ISSUE THREAD

**Issue by 16c7x** [puppetlabs/ilt-practitioner-issues#59]
## Describe the Bug
The instructions state
```
8. Create the [control-repo]/data/nodes/clientcert.yaml file and add data similar to what's shown in this image:
```
The solution states;
```
Example file: [control-repo]/data/clientcert.yaml
```

## Expected Behavior
The solution should say
```
Example file: [control-repo]/data/nodes/clientcert.yaml
```

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by martezr** [comment]
The solution has been updated to include the proper path for the file by adding the "nodes" directory to the path.
