### ISSUE TITLE
Lab 8.1 Create a custom fact - RUBYLIB step does not return expected output

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#66]
## Describe the Bug

https://puppet-kmo.gitbook.io/puppet-practitioner/-MPdvR5xZAI8pDW3UK6L/table-of-content/lesson-8-facts-and-functions/lab-8.1-create-a-custom-fact

Step to test fact using RUBYLIB does not work on PE2019.8 build - see also https://github.com/puppetlabs/ilt-practitioner-issues/issues/33

6\. Syntax check and test your new fact locally.
   - `/opt/puppetlabs/puppet/bin/ruby -c lib/facter/default_realm.rb`
   - `RUBYLIB="lib" facter default_realm`

Using `FACTERLIB` or `--custom-dir` (per documentation) yields expected results

```
[root@2288nix17 kerberos]# /opt/puppetlabs/puppet/bin/ruby -c lib/facter/default_realm.rb
Syntax OK
[root@2288nix17 kerberos]# RUBYLIB="lib" facter default_realm

[root@2288nix17 kerberos]# vi /etc/krb5.conf
[root@2288nix17 kerberos]# RUBYLIB="lib" facter default_realm

[root@2288nix17 kerberos]# FACTERLIB=./lib/facter facter default_realm
EXAMPLE.COM
[root@2288nix17 kerberos]# facter -p --custom-dir ./lib/facter default_realm
EXAMPLE.COM
[root@2288nix17 kerberos]# cat lib/facter/default_realm.rb
Facter.add("default_realm") do
  # setcode "/bin/awk '/^#/ {next} /default_realm/{print $NF}' /etc/krb5.conf"
  setcode "/bin/awk '/^([\t ]?[^#][\t ]?)default_realm/{print $NF}' /etc/krb5.conf"
end
[root@2288nix17 kerberos]# grep default_realm /etc/krb5.conf
 default_realm = EXAMPLE.COM
[root@2288nix17 kerberos]#
```

## Expected Behavior

Steps provided in lab should work.

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

## Additional Context

See also https://github.com/puppetlabs/ilt-practitioner-issues/issues/33

**Comment by josephoaks** [comment]
This lab works exactly as stated in the instructions and solutions guide.

PE: 2019.8.4
Puppet Agent: 6.19.1
Exact version from the classroom environment.

Output as follows showing it works as expected. The example on the Lab 8.1: Create a custom fact - Linux tab states "Using the command line to parse this value might look something like:" awk '/default_realm/{print $NF}' /etc/krb5.conf does return the commented line in the krb5.conf file. 

`[root@pirate-09nix0 modules]# cd kerberos/
[root@pirate-09nix0 kerberos]# mkdir -p lib/facter
[root@pirate-09nix0 kerberos]# vi lib/facter/default_realm.rb
[root@pirate-09nix0 kerberos]# cat lib/facter/default_realm.rb
Facter.add("default_realm") do
  confine :kernel => 'Linux'
  setcode "/bin/awk '/^#/ {next} /default_realm/{print $NF}' /etc/krb5.conf"
end
[root@pirate-09nix0 kerberos]# /opt/puppetlabs/puppet/bin/ruby -c lib/facter/default_realm.rb
Syntax OK
[root@pirate-09nix0 kerberos]# RUBYLIB="lib" facter default_realm

[root@pirate-09nix0 kerberos]#`

**Comment by golflimaechoecho** [comment]
@josephoaks is your output with default_realm commented in /etc/krb5.conf? - if that is the case then yes the output would be empty.

The bug was raised as RUBYLIB was still returning empty even after default_realm was uncommented, as shown in the output provided.

**Comment by josephoaks** [comment]
Yes, I see what you are saying, have modified the awk statement to better work, this was someone else code from a long time ago and since we no longer show the modification of the krb5.conf file using augeas it makes sense to set it to print something instead of being blank and being set later.
