### ISSUE TITLE
Lab 8.1 - Linux - awk command provided in solution doesn't work for the custom fact.

### ISSUE THREAD

**Issue by benjamin-robertson** [puppetlabs/ilt-practitioner-issues#75]
## Describe the Bug
The solution provides the following awk example.

**/bin/awk '/^#/ {next} /default_realm/{print $NF}' /etc/krb5.conf**

This is checking for the presence of a # at the start of the line (a commented line), if it does it skips that line. 
By default default_realm is not set in /etc/krb5.com as its commented out. 

We do not instruct students to uncomment the default_realm option in the krb5.conf file. 

## Expected Behavior
Either use a different value which isn't commented out. Or instruct students to uncomment the default realm.

The awk example provided in the lab **awk '/default_realm/{print $NF}' /etc/krb5.conf** also does not check for the presence of a comment. We probably shouldn't use this either, as it will return an invalid value.

## Steps to Reproduce
Implement the solution to the lab.

Fact will not be returned as default_realm is commented out. 

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by josephoaks** [comment]
This is intentional as it will be used in a later lab.
