### ISSUE TITLE
Diagrams/picture files still have old/harmful terminology

### ISSUE THREAD

**Issue by golflimaechoecho** [puppetlabs/ilt-practitioner-issues#92]
Text in slides has been updated to remove harmful terminology, however corresponding diagrams/picture files still reference "master", etc

This can be confusing when presenting as you're trying to avoid using harmful terminology (eg: referring to "primary server") while referencing/guiding the students through a diagram that still shows "master"/old terms.

**Comment by taraswenson** [comment]
Thanks for calling this out @golflimaechoecho. We have gone ahead and replaced the images that used harmful terminology in Puppet Practitioner.
